/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.invoices.dialogs;

import database.tables.Invoice;
import gui.utilities.table.invoicetable.InvoiceItemTableModel;
import java.text.DecimalFormat;
import javax.swing.SwingUtilities;
import tools.StringTools;

/**
 *
 * @author Hannes
 */
public class InvoiceDetailsDialog extends javax.swing.JDialog {

    private final Invoice model;
    private final InvoiceItemTableModel tableModel;
    
    /**
     * Creates new form InvoiceDetailsDialog
     */
    public InvoiceDetailsDialog(java.awt.Frame parent, boolean modal, Invoice invoice) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
	
	model = invoice;
	
	
        tableModel = new InvoiceItemTableModel(model.items());
        articleTableOutlet.setModel(tableModel);
	
	this.setTitle("Factuur - " + model.getNumber());
	
	loadModel();
    }
    
    private void loadModel(){
        lblNummer.setText("" + model.getNumber());
        lblKlasse.setText(model.getPriceCode());
        lblDate.setText(model.getDate());
	clientOutlet.setText(StringTools.capitalizeEach(model.getClient().getSortKey()));
        
        lblSave.setText(new DecimalFormat("0.00").format(model.getSave())+" %");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detail = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblNummer = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        clientOutlet = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblKlasse = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        articleTableOutlet = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblSave = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        edit = new javax.swing.JButton();
        close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        detail.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout(0, 2));

        jLabel6.setBackground(new java.awt.Color(242, 242, 242));
        jLabel6.setText("Nummer");
        jLabel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 3, 0));
        jLabel6.setOpaque(true);
        jPanel2.add(jLabel6);

        lblNummer.setBackground(new java.awt.Color(242, 242, 242));
        lblNummer.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        lblNummer.setOpaque(true);
        jPanel2.add(lblNummer);

        jLabel4.setText("Datum");
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 3, 0));
        jPanel2.add(jLabel4);

        lblDate.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanel2.add(lblDate);

        jLabel2.setBackground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("Klant");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 3, 0));
        jLabel2.setOpaque(true);
        jPanel2.add(jLabel2);

        clientOutlet.setBackground(new java.awt.Color(242, 242, 242));
        clientOutlet.setText("<hyperlink to client>");
        clientOutlet.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        clientOutlet.setOpaque(true);
        jPanel2.add(clientOutlet);

        jLabel3.setText("Prijsklasse");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 3, 0));
        jPanel2.add(jLabel3);

        lblKlasse.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanel2.add(lblKlasse);

        detail.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        articleTableOutlet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(articleTableOutlet);

        detail.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridLayout(0, 2));

        jLabel5.setText("Korting");
        jPanel1.add(jLabel5);
        jPanel1.add(lblSave);

        jLabel1.setText("Prijs");
        jPanel1.add(jLabel1);
        jPanel1.add(lblPrice);

        detail.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(detail, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        edit.setText("Wijzig...");
        jPanel4.add(edit);

        close.setText("Terug");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel4.add(close);

        jPanel3.add(jPanel4, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        disposeLater();
    }//GEN-LAST:event_closeActionPerformed

    private void disposeLater(){
	SwingUtilities.invokeLater(new Runnable() {

	    @Override
	    public void run() {
		dispose();
	    }
	});
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable articleTableOutlet;
    private javax.swing.JLabel clientOutlet;
    private javax.swing.JButton close;
    private javax.swing.JPanel detail;
    private javax.swing.JButton edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblKlasse;
    private javax.swing.JLabel lblNummer;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblSave;
    // End of variables declaration//GEN-END:variables
}
