/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.invoices;

import database.tables.Supplier;
import gui.MasterDetailViewController;
import gui.TabbedViewController;
import gui.invoices.controllers.ArticleViewController;
import gui.invoices.controllers.ClientViewController;
import gui.invoices.controllers.InvoiceViewController;
import java.awt.event.KeyEvent;
import java.util.HashMap;
import javax.swing.JPanel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Hannes
 */
public class InvoiceTabbedViewController extends javax.swing.JPanel implements TabbedViewController{

    private final int invoicesTabIndex = 0;
    private final int articlesTabIndex = 1;
    private final int clientsTabIndex = 2;
    
    private HashMap<Integer, MasterDetailViewController> tabs;
    
    /**
     * Creates new form RecipeTabbedViewController
     */
    public InvoiceTabbedViewController() {
        initComponents();
        
        tabs = new HashMap<Integer, MasterDetailViewController>();
	
	tabs.put(invoicesTabIndex, new InvoiceViewController());
	tabs.put(articlesTabIndex, new ArticleViewController());
	tabs.put(clientsTabIndex, new ClientViewController());
	
	invoiceTab.add(tabs.get(invoicesTabIndex).view());
	articleTab.add(tabs.get(articlesTabIndex).view());
	clientTab.add(tabs.get(clientsTabIndex).view());
	
	tabController.addChangeListener(new ChangeListener() {

	    @Override
	    public void stateChanged(ChangeEvent e) {
		tabs.get(tabController.getSelectedIndex()).electFirstResponder();
	    }
	});
        
    }
    
    public void selectAndSwitchToSupplier(Supplier supplier){
    }
    
    @Override
    public JPanel view(){
        return this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabController = new javax.swing.JTabbedPane();
        invoiceTab = new javax.swing.JPanel();
        articleTab = new javax.swing.JPanel();
        clientTab = new javax.swing.JPanel();

        setFocusable(false);
        setLayout(new java.awt.BorderLayout());

        tabController.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        tabController.setFocusable(false);

        invoiceTab.setFocusable(false);
        invoiceTab.setLayout(new java.awt.BorderLayout());
        tabController.addTab("Facturen", invoiceTab);

        articleTab.setFocusable(false);
        articleTab.setLayout(new java.awt.BorderLayout());
        tabController.addTab("Artikels", articleTab);

        clientTab.setFocusable(false);
        clientTab.setLayout(new java.awt.BorderLayout());
        tabController.addTab("Klanten", clientTab);

        add(tabController, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel articleTab;
    private javax.swing.JPanel clientTab;
    private javax.swing.JPanel invoiceTab;
    private javax.swing.JTabbedPane tabController;
    // End of variables declaration//GEN-END:variables

    @Override
    public void handleKeyEvent(KeyEvent evt) {
	throw new UnsupportedOperationException("Not supported yet.");
    }
}
